#!/bin/bash
# Atalho para funcoes Cronus-Commander - http://Cronus-Emulator.com [Raizen]
# Otimizacoes [Roberto]
# Modificacao de funcoes, adicao de funcoes e mudanca do nome para Cronus [Raizen]
arch=`/bin/arch`
versao="2.1"
case $1 in
	recompilar|compilar) 
		if [[ $arch == "x86_64" ]]; then
			echo $arch
			sh configure --enable-64bit --with-MYSQL_LIBS=/usr/lib64/libmysqlclient.so
		else
			sh configure --disable-64bit
		fi
		cpu=`grep -c ^processor /proc/cpuinfo`
		make clean
		if [ $cpu -lt 0 ]; then
			make -j$cpu all
		else
			make all
		fi
	;;
	'mapcache') 
		if [ ! -f Makefile ]; then
			$0 compilar
		fi
		make tools
		echo "Map_Cache compilado com sucesso!"
	;;
	'versao')
		echo "Cronus-Commander v$versao"
	;;
	'ligar')
		services=`ps aux | grep -v grep | grep -cE "map-server|login-server|char-server"`
		if [ $services -eq 0 ]; then
			exec ./login-server > /var/log/login-server.txt &
			exec ./char-server > /var/log/char-server.txt &
			exec ./map-server > /var/log/map-server.txt &
			sleep 5
			if [ $(ps aux | grep -v grep | grep -c map-server) -eq 1 ]; then
				echo "Map-server inicializado com sucesso!"
			fi
			if [ $(ps aux | grep -v grep | grep -c char-server) -eq 1 ]; then
				echo "Char-server inicializado com sucesso!"
			fi
			if [ $(ps aux | grep -v grep | grep -c login-server) -eq 1 ]; then
				echo "Login-server inicializado com sucesso!"
			fi
		else
			echo "O emulador ja foi iniciado!"
		fi
	;;
	'desligar')
		services=`ps aux | grep -v grep | grep -cE "map-server|login-server|char-server"`
		if [ $services -ge 3 ]; then
			killall -9 map-server char-server login-server
			sleep 5
			if [ $(ps aux | grep -v grep | grep -c map-server) -lt 1 ]; then
				echo "Map-server finalizado com sucesso!"
			fi
			if [ $(ps aux | grep -v grep | grep -c char-server) -lt 1 ]; then
				echo "Char-server finalizado com sucesso!"
			fi
			if [ $(ps aux | grep -v grep | grep -c login-server) -lt 1 ]; then
				echo "Login-server finalizado com sucesso!"
			fi
		else
			echo "O emulador ja foi desligado!"
		fi
	;;
	'reiniciar')
		$0 desligar
		$0 ligar
	;;
	'charlog')
		tail -f /var/log/char-server.txt
	;;
	'loginlog')
		tail -f /var/log/login-server.txt
	;;
	'maplog')
		tail -f /var/log/map-server.txt
	;;
	'auto')
		echo "Inicializando script para autoinicializacao, verificacao a cada 120 segundos"
		exec ./auto.sh &
	;;
	'tutorial')
		echo "As funcoes existentes atualmente neste script sao unicamente para ajudar o usuario na utilizacao de 
		comandos via shell. Para utilizar este script, basta que atraves do ssh acesse seu emulador e digite:
		./cronus PARAMETRO_DE_USO
		Para ver os parametros disponiveis digite:
		./cronus comandos
		Caso tenha qualquer duvida sobre este sistema, abra um topico de suporte em http://forum.cronus-emulator.com/"
	;;
	*) 
		echo "Os parametros disponiveis sao:
		ligar|desligar|reiniciar|compilar|recompilar|versao|mapcache|charlog|maplog|loginlog|tutorial|auto"
	;;
esac
